config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'bookaflight', to: 'flights#bookaflight'
  post 'bookaflight', to: 'flights#passbookaflight'
  get 'passbookaflight', to: 'flights#passbookaflight'
  post 'passbookaflight', to: 'flights#passbookaflight'

  resources :users
  resources :feedbacks
  resources :transactions
  resources :reservations
  resources :flights
  resources :airports

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :transactions, :dependent => :destroy
  has_many :reservations, :dependent => :destroy
  has_many :feedbacks, :dependent => :destroy
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  $five = "abc"
  # GET /flights or /flights.json
  def index
      @flights = Flight.all    
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @airport = Airport.all.map{ |u| [ u.airport_place ] }
    @flight = Flight.new
  end

  def bookaflight
      @flights = Flight.all
      
      @origin = @flights.map{ |u| [ u.origin_airport ] }.uniq
      @destination = @flights.map{ |u| [ u.destination_airport ] }.uniq
      @departure_dates = @flights.map{ |u|  u.departure_date unless u.departure_date < ( Date.today + 1.day )  }.uniq
      # @departure_dates = @flights.map{ |u|  u.departure_date   }.uniq

      @flight_number = "C0kEoBXcL5&g@W$2HC3k"
      @flight_capacity = 56
      @flight_price = 10

      @flight = Flight.new 
      
  end

  def passbookaflight
   @flights = $five
  end

  # GET /flights/1/edit
  def edit
    @airport = Airport.all.map{ |u| [ u.airport_place ] }
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    if(@flight.flight_number == "C0kEoBXcL5&g@W$2HC3k" )

      $five = Flight.all.select{ | flight | ( flight.origin_airport == @flight.origin_airport ) && ( flight.destination_airport == @flight.destination_airport ) && ( flight.departure_date == @flight.departure_date ) }
      respond_to do |format|
        if $five
          format.html { redirect_to '/passbookaflight', notice: "Flight search." }
          format.json { render :passbookaflight, status: :created, location: $five }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @flight.errors, status: :unprocessable_entity }
        end 
      end     
    else   

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end      
    end
  end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:flight_number, :origin_airport, :destination_airport, :departure_date, :departure_time, :flight_capacity, :flight_price)
    end  

  
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_bookaflight.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="field">
    <%= form.hidden_field :flight_number ,value:@flight_number %>     
  </div>
  
  <div class="field">
    <%= form.label :origin_airport %>
    <%= form.select(:origin_airport, options_for_select(@origin)) %>
  </div>

  <div class="field">
    <%= form.label :destination_airport %>
    <%= form.select(:destination_airport, options_for_select(@destination)) %>
  </div>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.select(:departure_date, options_for_select(@departure_dates)) %>
  </div>

<div class="field">   
    <%= form.hidden_field :departure_time ,value:Time.now %>    
  </div>
 
  <div class="field">   
    <%= form.hidden_field :flight_capacity ,value: @flight_capacity %>   
  </div>

  <div class="field">   
    <%= form.hidden_field :flight_price ,value:@flight_price %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_number %>
    <%= form.text_field :flight_number %>
  </div>

  <div class="field">
    <%= form.label :origin_airport %>
    <%= form.select(:origin_airport, options_for_select(@airport)) %>
  </div>

  <div class="field">
    <%= form.label :destination_airport %>
    <%= form.select(:destination_airport, options_for_select(@airport)) %>
  </div>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :departure_time %>
    <%= form.time_select :departure_time %>
  </div>

  <div class="field">
    <%= form.label :flight_capacity %>
    <%= form.number_field :flight_capacity %>
  </div>

  <div class="field">
    <%= form.label :flight_price %>
    <%= form.number_field :flight_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/bookaflight.html.erb
<h1>Book A Flight</h1>

<%= render 'bookaflight', flight: @flight %>

<%= link_to 'Back', root_path %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight number</th>
      <th>Origin airport</th>
      <th>Destination airport</th>
      <th>Departure date</th>
      <th>Departure time</th>
      <th>Flight capacity</th>
      <th>Flight price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td><%= flight.origin_airport %></td>
        <td><%= flight.destination_airport %></td>
        <td><%= flight.departure_date %></td>
        <td><%= flight.departure_time %></td>
        <td><%= flight.flight_capacity %></td>
        <td><%= flight.flight_price %></td>

        <% if current_user.admin %>

          <td><%= link_to 'Book', new_reservation_path(:flight_id => flight.id, :user_id => current_user.id) %></td>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% else %>

          <td><%= link_to 'Book', new_reservation_path(:flight_id => flight.id, :user_id => current_user.id) %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/passbookaflight.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight number</th>
      <th>Origin airport</th>
      <th>Destination airport</th>
      <th>Departure date</th>
      <th>Departure time</th>
      <th>Flight capacity</th>
      <th>Flight price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td><%= flight.origin_airport %></td>
        <td><%= flight.destination_airport %></td>
        <td><%= flight.departure_date %></td>
        <td><%= flight.departure_time %></td>
        <td><%= flight.flight_capacity %></td>
        <td><%= flight.flight_price %></td>

        <% if current_user.admin %>

          <td><%= link_to 'Book', new_reservation_path(:flight_id => flight.id, :user_id => current_user.id) %></td>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% else %>

          <td><%= link_to 'Book', new_reservation_path(:flight_id => flight.id, :user_id => current_user.id) %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight number:</strong>
  <%= @flight.flight_number %>
</p>

<p>
  <strong>Origin airport:</strong>
  <%= @flight.origin_airport %>
</p>

<p>
  <strong>Destination airport:</strong>
  <%= @flight.destination_airport %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @flight.departure_date %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @flight.departure_time %>
</p>

<p>
  <strong>Flight capacity:</strong>
  <%= @flight.flight_capacity %>
</p>

<p>
  <strong>Flight price:</strong>
  <%= @flight.flight_price %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>