config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'bookaflight', to: 'flights#bookaflight'
  post 'bookaflight', to: 'flights#passbookaflight'
  get 'passbookaflight', to: 'flights#passbookaflight'
  post 'passbookaflight', to: 'flights#passbookaflight'

  resources :users
  resources :feedbacks
  resources :transactions
  resources :reservations
  resources :flights
  resources :airports

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Alpha Flight Booking Portal</h1>
<p>Fly with pride</p>
<% if current_user %>
  Logged in as <%= current_user.name %>. <br><br>
  <% if current_user.admin %>
    <%= link_to 'View or Edit user information', users_path %><br>
    <%= link_to 'Add or Remove Airport ', airports_path %><br>
    <%= link_to 'Book / Manage flights', flights_path %><br>
    <%= link_to 'View All reservations', reservations_path %><br>
    <%= link_to 'View Feedback', feedbacks_path %><br>

  <% else %>
    <%= link_to 'View or Edit your information', users_path %><br>
    <%= link_to 'Book new flight', '/bookaflight' %><br>
    <%= link_to 'View your reservations', reservations_path %><br>
    <%= link_to 'View Feedback', feedbacks_path %><br>

  <% end %>
  <%= link_to "Logout", 'logout' %><br>
<% else %>
  <%= link_to "Signup", 'signup' %> or
  <%= link_to "Login", 'login' %>
<% end %>