config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'bookaflight', to: 'flights#bookaflight'
  post 'bookaflight', to: 'flights#passbookaflight'
  get 'passbookaflight', to: 'flights#passbookaflight'
  post 'passbookaflight', to: 'flights#passbookaflight'

  resources :users
  resources :feedbacks
  resources :transactions
  resources :reservations
  resources :flights
  resources :airports

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: %i[ show edit update destroy ]

  # GET /airports or /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1 or /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports or /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: "Airport was successfully created." }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1 or /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: "Airport was successfully updated." }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1 or /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: "Airport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.require(:airport).permit(:airport_place)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_with(model: airport) do |form| %>
  <% if airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
        <% airport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :airport_place %>
    <%= form.text_field :airport_place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airports</h1>

<table>
  <thead>
    <tr>
      <th>Airport place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= airport.airport_place %></td>
        <td><%= link_to 'Show', airport %></td>
        <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
        <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airport place:</strong>
  <%= @airport.airport_place %>
</p>

<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>